spring:
  config:
    import: "optional:configserver:"
  application:
    name: "OnlineMovieStoreInventory"

eureka:
  client:
    healthcheck:
      enabled: true
server:
  port: 8080
  servlet.contextPath: /api/movies

