spring:
  config:
    import: "optional:configserver:"
  application:
    name: "OnlineMovieStoreInventory"

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.dyurekdeler.OnlineMovieStoreInventory.serializer.KafkaModelDeserializer

    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    healthcheck:
      enabled: true
server:
  port: 8080
  servlet.contextPath: /api/movies

