spring:
  config:
    import: "optional:configserver:"
  application:
    name: "OnlineMovieStoreCustomer"

eureka:
  client:
    healthcheck:
      enabled: false
server:
  port: 8082
  servlet.contextPath: /api/customers
